Work
StasLina/StasLinSnake pull request #1
Opened 2023-10-25 06:42 UTC by StasLina

2023-10-25 06:42 UTC, StasLina commented
Самая лучшая змейка

2023-11-22 07:35 UTC, Silmarill requested changes

2023-11-22 07:35 UTC, Silmarill commented on GlobalVars.cpp
> +    if (pos_x >= GlobalVars::x_size || pos_y >= GlobalVars::y_size) {
добавь пустую строку между блоками с if

2023-11-22 07:35 UTC, Silmarill commented on GlobalVars.cpp
> +        ++n;
однобуквенная переменная

2023-11-22 07:35 UTC, Silmarill commented on GlobalVars.cpp
> +        ++row;
rowIndex

2023-11-22 07:35 UTC, Silmarill commented on GlobalVars.h
> +    short x=0, y=0;
пробелы вокруг операторов =

2023-11-22 07:35 UTC, Silmarill commented on GlobalVars.h
> +    static bool isGameOver;
смешиваешь стили нейминга - выбери либо змеиный, либо верблюжий

2023-11-22 07:35 UTC, Silmarill commented on GlobalVars.h
> +    static const char eat;
неудачное имя переменной foodSymbol

2023-11-22 07:35 UTC, Silmarill commented on GlobalVars.h
> +    static long speed_time;
неудачный нейминг 
delayBetweenRefresh?
updateTime?

2023-11-22 07:35 UTC, Silmarill commented on GlobalVars.h
> +    static bool proverka_empty(const char& elm,bool set_eat=true) {
translit nedopuskaetsya

2023-11-22 07:35 UTC, Silmarill commented on GlobalVars.h
> +        switch (elm) {
что за elm?

2023-11-22 07:35 UTC, Silmarill commented on GlobalVars.h
> +        case '#': return false;
рекомендуется оформлять break  даже если в ветке единственный return

2023-11-22 07:35 UTC, Silmarill commented on GlobalVars.h
> +            if (set_eat) {
неудачный нейминг

2023-11-22 07:35 UTC, Silmarill commented on MapController.cpp
> +//��������� ��� �� �����
//äîáàâëÿåì åäó íà êàðòó

2023-11-22 07:35 UTC, Silmarill commented on MapController.cpp
> +            is_not_empty = false;
сложно

2023-11-22 07:35 UTC, Silmarill commented on MapController.cpp
> +    for (int j = 0; j != my_indent.top; ++j) {
индексы i j k - дурной тон
используй полные имена

2023-11-22 07:35 UTC, Silmarill commented on MapController.cpp
> +        for (short cur_col = 0; cur_col != GlobalVars::x_size; ++cur_col) {
currentColoumn

2023-11-22 07:35 UTC, Silmarill commented on MapController.cpp
> +        for (short cur_col = 0; cur_col != GlobalVars::x_size; ++cur_col) {
не жалей пустых строк для отдельных логических частей
код читается монолитно

2023-11-22 07:35 UTC, Silmarill commented on MapController.cpp
> +            char ch=(*score_snake)->GetModel()->GetModelSegment(0).data.data;
= не обрамлено пробелами

2023-11-22 07:35 UTC, Silmarill commented on MapController.cpp
> +    for (int j = 0; j != my_indent.bot; j++) {
правые кресты

2023-11-22 07:35 UTC, Silmarill commented on MapController.h
> +            }
} else {

2023-11-22 07:35 UTC, Silmarill commented on MapController.h
> +        int max_col = 0;
columnCount?

2023-11-22 07:35 UTC, Silmarill commented on MapController.h
> +            ++smth_elm;
???

2023-11-22 07:35 UTC, Silmarill commented on MapController.h
> +class MapController
class MapController {
не отрывай скобку

2023-11-22 07:35 UTC, Silmarill commented on MapController.h
> +    void Run(){
void Run()[пробел]{

2023-11-22 07:35 UTC, Silmarill commented on MapController.h
> +    void Draw();
либо lowerCamelCase либо UpperCamelCase
не смешивай

2023-11-22 07:35 UTC, Silmarill commented on MapController.h
> +    void AddSnake() {
AddPartToSnake() ?

2023-11-22 07:35 UTC, Silmarill commented on MapController.h
> +    void time_move() {
??

2023-11-22 07:35 UTC, Silmarill commented on SnakeController.cpp
> +	if (is_eat) {
is_eat - является едой

2023-11-22 07:35 UTC, Silmarill commented on SnakeController.cpp
> +	new_oren = smth_or;
new_oren = smth_or;  -->> newOrientation = smthOrientation

2023-11-22 07:35 UTC, Silmarill commented on SnakeController.cpp
> +	if (orent_changed) {
orent_changed --> didOrientationChange

2023-11-22 07:35 UTC, Silmarill commented on SnakeController.h
> +		for (short i = 0; i != pos_x; ++i,++smth_seg);
нечитаемый код

2023-11-22 07:35 UTC, Silmarill commented on SnakeController.h
> +	std::list <SnakeSegment> body_snake;
body_snake -->>> snakeBody

2023-11-22 07:35 UTC, Silmarill commented on SnakeController.h
> +		snake_die = true;
isAlive = false

2023-11-22 07:35 UTC, Silmarill commented on main.cpp
> +    bool repeat = true;
???

2023-12-26 02:54 UTC, closed without merging